### ISSUE TITLE
未激活钱包问题

### ISSUE THREAD

**Issue by haiboliu007** [eostoken/wallet#128]
1.创建未激活的账号   创建完没弹提示
2.钱包页中切换钱包中没显示，未激活钱包例图：
![image](https://user-images.githubusercontent.com/39845951/42158116-27f9e316-7e22-11e8-9078-a59835173540.png)

3.在使用未激活账户过程中没提示  （目前添加购买跳转）例图：
![image](https://user-images.githubusercontent.com/39845951/42158134-31b12054-7e22-11e8-8bab-b18712f199c6.png)

4.创建完了不能立马删除必须杀死APP再打开 例图：
![image](https://user-images.githubusercontent.com/39845951/42158170-4d96b5ae-7e22-11e8-864b-744d7307fc1d.png)

5.未激活（状态字框也要红的）

**Comment by eostoken** [comment]
激活标识没做
![image](https://user-images.githubusercontent.com/37651836/42203502-84634ba6-7ed1-11e8-9851-32aaccbf136b.png)

**Comment by eostoken** [comment]
![image](https://user-images.githubusercontent.com/37651836/42205211-6054fdf4-7ed6-11e8-8eed-678f40fe28bb.png)
点击（未备份）标识跳转钱包备份，目前备份还没做
