### ISSUE TITLE
修改创建EOS账号规则

### ISSUE THREAD

**Issue by eostoken** [eostoken/wallet#151]
1.积分不足100，可联系小助手购买积分进行激活账号  弹框：（1.你当前的积分不足，无法获得免费激活账户权益；2.你可以联系官方小助手购买积分进行激活）
2.没有登录，不可创建账号，需提示先进行登录 吐丝：（请先登录）
3.每个账户只请允许创建一个账号 吐丝：（您已创建过账号, 留点机会给别人吧！）
4.如果创建的账号被占用，提示 吐丝：（ 该账号已被占用！）

**Comment by haiboliu007** [comment]
已处理
