### ISSUE TITLE
创建钱包问题

### ISSUE THREAD

**Issue by caiyuanzi2018** [eostoken/wallet#155]
BUG1：创建钱包密码提示输入的提示文件是加密的；
![image](https://user-images.githubusercontent.com/37617145/42308703-f1395eda-8068-11e8-924f-2ecf5edaa78f.png)

BUG2：创建钱包完成后的提示有误！；

![image](https://user-images.githubusercontent.com/37617145/42308752-18fbc02a-8069-11e8-83ac-b11fbc06dedf.png)

**Comment by marcoLuo** [comment]
不修改
