### ISSUE TITLE
资源管理输入错误的数量后，卡死了；

### ISSUE THREAD

**Issue by caiyuanzi2018** [eostoken/wallet#166]
环境：ios
“计算资源”，“网络资源”，“内存资源”
![image](https://user-images.githubusercontent.com/37617145/42314248-36394ac8-8077-11e8-8097-ca5be4da3ec9.png)
![image](https://user-images.githubusercontent.com/37617145/42314294-4dba6a7e-8077-11e8-84a2-4c5e9920ed8f.png)

**Comment by Ben002** [comment]
#148 解决了这个问题
