### ISSUE TITLE
客服反应测试网注册的账户有用户转入EOS了（包括未激活需要修改为不可进入转账并弹窗提示）

### ISSUE THREAD

**Issue by haiboliu007** [eostoken/wallet#192]

**Comment by haiboliu007** [comment]
弹窗     提示：该账号为测试网创建，非主网账号，不支持此操作！

**Comment by haiboliu007** [comment]
![image](https://user-images.githubusercontent.com/39845951/42372028-bf840ab2-8143-11e8-9273-78f468ef2199.png)

**Comment by marcoLuo** [comment]
如果是以前的账户，没有未激活标识的，则显示未激活，需要点击激活才能使用
