### ISSUE TITLE
创建钱包的提示说明行距还是很大，需要改小一点

### ISSUE THREAD

**Issue by haiboliu007** [eostoken/wallet#193]
![image](https://user-images.githubusercontent.com/39845951/42374350-7b77166e-814a-11e8-8ee6-6ee7631413b8.png)

**Comment by haiboliu007** [comment]
![image](https://user-images.githubusercontent.com/39845951/42374407-a6bd59b4-814a-11e8-90ca-cd36d77ac35c.png)

**Comment by caiyuanzi2018** [comment]
PASS
