### ISSUE TITLE
添加资产搜索页面修改文字

### ISSUE THREAD

**Issue by haiboliu007** [eostoken/wallet#196]
把“合约地址”改为“合约账户”
![image](https://user-images.githubusercontent.com/39845951/42406442-4a3f1e76-81da-11e8-8db7-581f529053d8.png)
![image](https://user-images.githubusercontent.com/39845951/42406446-530c5d52-81da-11e8-8b96-3d235a19ca4c.png)

**Comment by bille18** [comment]
已解决

**Comment by caiyuanzi2018** [comment]
PASS
