### ISSUE TITLE
转账  转出添加信息显示

### ISSUE THREAD

**Issue by haiboliu007** [eostoken/wallet#197]
![image](https://user-images.githubusercontent.com/39845951/42497294-75ca54d8-845b-11e8-873b-a9574894b217.png)

**Comment by marcoLuo** [comment]
信息还是按v2.1.6的，可以把框样式修改成这样

**Comment by Ben002** [comment]
功能已完成提交，详见：commit 77dc0eb9e2622eb501183a70464ab1d8ec9f68d2
#197 修改转账弹框的出现方式

![image](https://user-images.githubusercontent.com/20814894/42546197-e95d6ae6-84ee-11e8-8ac5-f91f08bf1247.png)
