### ISSUE TITLE
创建账户优化建议

### ISSUE THREAD

**Issue by marcoLuo** [eostoken/wallet#2]
建议在钱包界面，如果没有账户时，直接加个按钮让用户可以点击直接创建钱包。
![2018-05-31 22-36-41](https://user-images.githubusercontent.com/34716509/40788653-26a5ba16-6523-11e8-9e22-59256e6bedca.png)

**Comment by haiboliu007** [comment]
切换到这个页面强制  弹出 是否创建一个新的钱包    这样会不会好一点

**Comment by eostoken** [comment]
可以的，这几天会优化一版出来
