### ISSUE TITLE
转账 返回提示  交易失败

### ISSUE THREAD

**Issue by haiboliu007** [eostoken/wallet#200]
提示：网络拥堵，交易可能延时~

**Comment by marcoLuo** [comment]
后台捕获到网络超时情况，返回相关提示“网络拥堵，交易可能延时，5分钟后可通过查询交易记录查询交易成功与否”。 @haiboliu007

**Comment by marcoLuo** [comment]
网络拥堵，交易可能延时，5分钟后可通过查询交易记录确认是否成功

**Comment by marcoLuo** [comment]
暂不解决
