### ISSUE TITLE
添加导入私钥教程链接

### ISSUE THREAD

**Issue by haiboliu007** [eostoken/wallet#211]
![image](https://user-images.githubusercontent.com/39845951/42432713-872222b6-837e-11e8-8b6e-887c28858875.png)

**Comment by haiboliu007** [comment]
跳转内容由运营部提供

**Comment by Ben002** [comment]
显示格式大致如下：
![image](https://user-images.githubusercontent.com/20814894/42559882-f1e4f510-8527-11e8-943f-9d2e0a698ba3.png)
![image](https://user-images.githubusercontent.com/20814894/42559904-fe0ffb64-8527-11e8-8770-82878d8dd0fd.png)

**Comment by caiyuanzi2018** [comment]
PASS
