### ISSUE TITLE
请问，我打包测试时，在导入私钥时，debug版本可以识别异常私钥，release版本无法识别异常私钥？

### ISSUE THREAD

**Issue by myx75** [eostoken/wallet#220]
请问，我打包测试时，在导入私钥时，debug版本可以识别异常私钥，release版本无法识别异常私钥。
感觉就是的检查私钥函数一直没有返回，是release版本需要什么特别的配置吗？
  Eos.checkPrivateKey(this.state.activePk, (r) => {
    if (!r.isSuccess) {
      EasyToast.show('私钥格式不正确');
      return;
    }
    this.createWalletByPrivateKey(this.state.activePk, this.state.activePk);
  });

**Comment by marcoLuo** [comment]
Release版本需要把eosjs.html打包到android的assets目录下：android/app/src/main/assets/eosjs.html @myx75

**Comment by myx75** [comment]
你好，我在项目根目录：把node_modules/react-native-eosjs/src/eosjs.html拷贝到android/app/src/main/assets/eosjs.html，打包后测试问题依旧，是我操作错误了吗，还是尚缺少其它配置？

**Comment by superzitao** [comment]
这个问题是react-native的一个打包的bug，在安卓版本内如果是使用的html文件作为库的话需要把html文件放置到assets目录下，同时修改库文件里面的source。
具体修改如下：
路径：node_module/react-native-eosjs/src/index.js

const iosPlatform = Platform.OS === 'IOS' ? 'true' : 'false'; //放到 import api from './eosapi' 下面一行

//文件的最后
  render() {
    return (<View style={{ flex: 1, height: 0, zIndex: -999999, position: 'absolute' }}>
    <WebView ref="eosjs" style={{ height: 0, width: 0, backgroundColor: 'transparent' }} 
    source={iosPlatform === 'true' ? require('./eosjs.html') : { 'uri': 'file:///android_asset/eosjs.html' }}
    // source={require('./eosjs.html')} 
    onMessage={(e) => { this.onMessage(e) }} 
    /></View>);
  }

**Comment by myx75** [comment]
这样打包有效！谢谢指教。
