### ISSUE TITLE
删除未激活账号提示

### ISSUE THREAD

**Issue by haiboliu007** [eostoken/wallet#221]
![image](https://user-images.githubusercontent.com/39845951/42496767-add46726-8459-11e8-8394-8b8c53820aa7.png)

若您的积分达到100以上，创建的账号存在未
激活现象，请不要删除！若删除激活中的账号
将可能给您带来损失！

建议您间隔5-10分钟，再次点击激活账户！
如还是不能激活帐号，请联系客服！

**Comment by caiyuanzi2018** [comment]
PASS
