### ISSUE TITLE
快讯分享版式修改

### ISSUE THREAD

**Issue by haiboliu007** [eostoken/wallet#248]
![image](https://user-images.githubusercontent.com/39845951/42740657-04d6825c-88dd-11e8-9982-99fec91a7a14.png)
![image](https://user-images.githubusercontent.com/39845951/42740671-3201e38e-88dd-11e8-9a13-842addaba6b5.png)
![image](https://user-images.githubusercontent.com/39845951/42741594-4fc2f63e-88e6-11e8-9972-2e667921cdad.png)

**Comment by bille18** [comment]
已解决.
