### ISSUE TITLE
钱包界面添加隐藏资产显示功能

### ISSUE THREAD

**Issue by haiboliu007** [eostoken/wallet#270]
![image](https://user-images.githubusercontent.com/39845951/42876251-affc4ff4-8ab8-11e8-92d1-7b6d237c9d0a.png)
![image](https://user-images.githubusercontent.com/39845951/42876346-f13211c0-8ab8-11e8-9ee9-cadfd83b6b78.png)

**Comment by caiyuanzi2018** [comment]
pass
