### ISSUE TITLE
二维码创建帐号格式

### ISSUE THREAD

**Issue by haiboliu007** [eostoken/wallet#274]
{"type":8,"data":{"account":"zitao1234511","action":"createAccount","active":"EOS5TnDobewWE2UfzwbPn4MWqZNRdV3vDvJoTDouT7eYEH3Diuz88","foundation":"EOS","owner":"EOS5TnDobewWE2UfzwbPn4MWqZNRdV3vDvJoTDouT7eYEH3Diuz88"}}

**Comment by marcoLuo** [comment]
暂不使用这种格式，我们的二维码带eos数量
