### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by guomingyi** [eostoken/wallet#279]
如下提示：
系统：ubuntu 16.04

$ npm i
npm WARN optional Skipping failed optional dependency /sane/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN @babel/plugin-check-constants@7.0.0-beta.38 requires a peer of @babel/core@7.0.0-beta.38 but none was installed.
npm WARN react-native-qrcode-svg@5.1.0 requires a peer of react-native-svg@^5.4.1 but none was installed.

$ npm start

11 silly lifecycle eostoken@0.0.1~start: Args: [ '-c',
11 silly lifecycle   'node node_modules/react-native/local-cli/cli.js start' ]
12 silly lifecycle eostoken@0.0.1~start: Returned: code: 1  signal: null
13 info lifecycle eostoken@0.0.1~start: Failed to exec start script
14 verbose stack Error: eostoken@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid eostoken@0.0.1
16 verbose cwd /home/mingyiguo/work/eos/wallet
17 error Linux 4.13.0-45-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v4.2.6
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error eostoken@0.0.1 start: `node node_modules/react-native/local-cli/cli.js start`
22 error Exit status 1
23 error Failed at the eostoken@0.0.1 start script 'node node_modules/react-native/local-cli/cli.js start'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the eostoken package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node node_modules/react-native/local-cli/cli.js start
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs eostoken
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls eostoken
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

帮忙看下是哪里导致的问题？

**Comment by marcoLuo** [comment]
我们在ubuntu下使用的npm和node版本如下，更新下试下，应该没问题的
npm version:3.10.10
node version:v6.11.2

**Comment by guomingyi** [comment]
ok，谢谢，我升级版本试试。
