### ISSUE TITLE
是否有详细一点的使用文档？npm start后没反应了

### ISSUE THREAD

**Issue by guomingyi** [eostoken/wallet#286]
您好，
升级npm和node版本后，没有报错了，提示如下：
$ npm start

> eostoken@0.0.1 start /home/xx/work/eos/wallet
> node node_modules/react-native/local-cli/cli.js start

Scanning folders for symlinks in /home/xx/work/eos/wallet/node_modules (17ms)
┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│  Running Metro Bundler on port 8081.                                         │
│                                                                              │
│  Keep Metro running while developing on any JS projects. Feel free to        │
│  close this tab and run your own Metro instance if you prefer.               │
│                                                                              │
│  https://github.com/facebook/react-native                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

Looking for JS files in
   /home/xx/work/eos/wallet 

Metro Bundler ready.

Loading dependency graph, done.

然后就没反应了，然后我参考使用：
$ npm run android/react-native run-android
npm ERR! Linux 4.13.0-45-generic
npm ERR! argv "/opt/node-v6.11.2-linux-x64/bin/node" "/opt/node-v6.11.2-linux-x64/bin/npm" "run" "android/react-native" "run-android"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10

npm ERR! missing script: android/react-native
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xx/work/eos/wallet/npm-debug.log

########################################################
我应该如何进入钱包用户界面？是否有详细一点的使用文档？

新手，请多包涵。

**Comment by superzitao** [comment]
你的运行步奏应该是
npm install
然后：
 react-native run-android
这样的吗

**Comment by guomingyi** [comment]
你的运行步奏应该是
npm install
然后：
react-native run-android
这样的吗
-----------------------》

我的操作步骤是：
1》$ npm i
2》$ npm run android/react-native run-android

完整记录如下：

$ npm i
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.3 (node_modules/sane/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @babel/plugin-check-constants@7.0.0-beta.38 requires a peer of @babel/core@7.0.0-beta.38 but none was installed.
npm WARN react-native-qrcode-svg@5.1.0 requires a peer of react-native-svg@^5.4.1 but none was installed.
mingyiguo@mingyiguo:~/work/eos/wallet$ npm run android/react-native run-android
npm ERR! Linux 4.15.0-29-generic
npm ERR! argv "/opt/node-v6.11.2-linux-x64/bin/node" "/opt/node-v6.11.2-linux-x64/bin/npm" "run" "android/react-native" "run-android"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10

npm ERR! missing script: android/react-native
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mingyiguo/work/eos/wallet/npm-debug.log

**Comment by guomingyi** [comment]
提示这个脚本不存在： npm ERR! missing script: android/react-native
代码是最新7.20的

**Comment by superzitao** [comment]
步骤2 你运行react-native run-android就可以了
