### ISSUE TITLE
RAM交易界面修改

### ISSUE THREAD

**Issue by haiboliu007** [eostoken/wallet#307]
![image](https://user-images.githubusercontent.com/39845951/43374445-516a4698-93e2-11e8-8217-0e088883f17b.png)

**Comment by haiboliu007** [comment]
买卖内存的时候，单为改为 KB，输入的位置，最好也加一个 金额（单价）

**Comment by marcoLuo** [comment]
改为1小时、1天、7天、一个月

**Comment by anonymoustoken** [comment]
最小单位一小时肯定不行的，最小单位，五分钟感觉会比较好，因为人家拿着抄短线呢。

**Comment by haiboliu007** [comment]
用了新的插件

**Comment by caiyuanzi2018** [comment]
没做
