### ISSUE TITLE
IOS备份钱包提示

### ISSUE THREAD

**Issue by haiboliu007** [eostoken/wallet#313]
![image](https://user-images.githubusercontent.com/39845951/43390231-3edbc694-9420-11e8-8c18-78ff13988aac.png)
没有备份到钱包页就提示！点击备份就跳转到备份钱包去

**Comment by anonymoustoken** [comment]
红色的这个3角行 改成黄色的会不会好一些。

**Comment by caiyuanzi2018** [comment]
pass
