### ISSUE TITLE
创建账号添加一个随机选号按钮

### ISSUE THREAD

**Issue by haiboliu007** [eostoken/wallet#314]
方便选号困难用户使用，警告的样式也改了
![image](https://user-images.githubusercontent.com/39845951/43456694-0a546dcc-94f7-11e8-975c-0769862f8888.png)

**Comment by anonymoustoken** [comment]
直接写随机连个字 感觉更好，现在这个样子反而不知道 这个按钮是做什么的。

**Comment by caiyuanzi2018** [comment]
pass
