### ISSUE TITLE
添加资产功能升级

### ISSUE THREAD

**Issue by haiboliu007** [eostoken/wallet#319]
1. 代币列表添加发行合约账号信息

**Comment by haiboliu007** [comment]
![image](https://user-images.githubusercontent.com/39845951/43442256-04541192-94d0-11e8-986b-6c809514f0bd.png)
![image](https://user-images.githubusercontent.com/39845951/43442277-151933e0-94d0-11e8-9526-6a7e38dbd4cd.png)

**Comment by haiboliu007** [comment]
改成合约账户

**Comment by bille18** [comment]
已解决

**Comment by caiyuanzi2018** [comment]
pass
