### ISSUE TITLE
转账交易记录延迟

### ISSUE THREAD

**Issue by marcoLuo** [eostoken/wallet#336]

**Comment by marcoLuo** [comment]
交易未确认时在交易记录里显示红色‘未确认’，交易确认后为正常交易记录显示

**Comment by haiboliu007** [comment]
![image](https://user-images.githubusercontent.com/39845951/43619917-bc7f4294-9702-11e8-8c27-a66d800f807e.png)

**Comment by caiyuanzi2018** [comment]
pass
