### ISSUE TITLE
内存交易界面，输入框输入规则没有限制了。

### ISSUE THREAD

**Issue by caiyuanzi2018** [eostoken/wallet#360]
![image](https://user-images.githubusercontent.com/37617145/43695841-8da74652-996d-11e8-8785-f75198a023b2.png)

**Comment by marcoLuo** [comment]
只要不显示ＮＡＮ即可，建议输入格式不对ＮＡＮ时显示为０

**Comment by bille18** [comment]
已按建议解决。
