### ISSUE TITLE
分享资讯顶部图片修改

### ISSUE THREAD

**Issue by haiboliu007** [eostoken/wallet#397]
分享快讯海报，最上方“ET快讯”中的ET较为不和谐，建议沟通下换个字体
![image](https://user-images.githubusercontent.com/39845951/44130499-8a02eb72-a080-11e8-9266-612af450dd1b.png)

**Comment by bille18** [comment]
已经解决，关闭.

**Comment by caiyuanzi2018** [comment]
pass
