### ISSUE TITLE
添加赎回问题解决页面

### ISSUE THREAD

**Issue by haiboliu007** [eostoken/wallet#424]
![image](https://user-images.githubusercontent.com/39845951/44337259-a25af400-a4ac-11e8-8742-517c6927ee3f.png)

![image](https://user-images.githubusercontent.com/39845951/44337127-1c3ead80-a4ac-11e8-8fae-85f6ab4f0995.png)

**Comment by marcoLuo** [comment]
已解决

**Comment by caiyuanzi2018** [comment]
pass
