### ISSUE TITLE
注册用户过程页面报错，缺少公钥？出错位置：AlgoUtil.js 第28行，rsa.setPublicString(puk);

### ISSUE THREAD

**Issue by myx75** [eostoken/wallet#440]
编译开源版本APP测试iOS注册用户时，报错：Unhandled JS Exception: JSON Parse error: Unexpected identifier "undefined"
查看调用栈发现
出错位置：AlgoUtil.js 第28行，rsa.setPublicString(puk);
出错原因：index.js里调用encryptedMsg时没有给第二个参数put，而且搜索出来的所有encryptedMsg调用都没有给出第二个参数；
请问需要配置公钥puk吗，还是需要修改encryptedMsg函数？谢谢

**Comment by marcoLuo** [comment]
encryptedMsg 这个地方直接返回msg值就好，也就是直接return msg;。目前使用的都是https通讯，这块可以不用再使用rsa加密通讯了，当然加多这块加密会更好。
