### ISSUE TITLE
按照正常流程，编译过程中出现这个错误

### ISSUE THREAD

**Issue by Arielce** [eostoken/wallet#472]
* What went wrong:
A problem occurred evaluating project ':react-native-linear-gradient'.
> Could not find method compileOnly() for arguments [com.facebook.react:react-native:+] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by marcoLuo** [comment]
我这已经确认了，react-native-linear-gradient的库你换成2.4.0的就没有问题了@Arielce
