### ISSUE TITLE
支付成功界面--点击分享给您的朋友  上下页优化。

### ISSUE THREAD

**Issue by caiyuanzi2018** [eostoken/wallet#541]
![image](https://user-images.githubusercontent.com/37617145/45347491-ceb2ed80-b5de-11e8-90fe-63a9fdc42798.png)

**Comment by yugangxiang** [comment]
![10_23_36__09_12_2018](https://user-images.githubusercontent.com/22267925/45398355-5ac42400-b676-11e8-8ec3-f758a216b3a6.jpg)
