### ISSUE TITLE
只输入了一次密码 点击确认 提示信息的方式不对（游戏方的问题）

### ISSUE THREAD

**Issue by caiyuanzi2018** [eostoken/wallet#609]
![image](https://user-images.githubusercontent.com/37617145/47421259-cc81a880-d7b2-11e8-8278-361a1e4960c9.png)

**Comment by bille18** [comment]
这是游戏网页自己提示的，非SDK控制。Fixed #609

**Comment by bille18** [comment]
Fixed #609
