### ISSUE TITLE
【安卓】多个页面不支持硬件返回键

### ISSUE THREAD

**Issue by caiyuanzi2018** [eostoken/wallet#615]
![image](https://user-images.githubusercontent.com/37617145/47599309-f10d9880-d9dd-11e8-9e04-39347aff33de.png)
![image](https://user-images.githubusercontent.com/37617145/47599356-ea335580-d9de-11e8-94f1-8f712064ce89.png)

**Comment by bille18** [comment]
已解决,Fixed #615
