### ISSUE TITLE
【安卓】界面部分手机不兼容

### ISSUE THREAD

**Issue by caiyuanzi2018** [eostoken/wallet#617]
![image](https://user-images.githubusercontent.com/37617145/47600256-e4df0680-d9f0-11e8-8eb4-e9ef72a6a19c.png)

![image](https://user-images.githubusercontent.com/37617145/47600267-ffb17b00-d9f0-11e8-9a04-09869572a71e.png)

**Comment by yugangxiang** [comment]
已解决，  #602 Eos Token钱包部分 改版
