### ISSUE TITLE
交易详情 界面右侧分享功能点击没有响应；   区块高度 一直是未确认状态

### ISSUE THREAD

**Issue by caiyuanzi2018** [eostoken/wallet#636]
![image](https://user-images.githubusercontent.com/37617145/47660160-65f4f400-dbd1-11e8-801c-a52f66654cc0.png)
![image](https://user-images.githubusercontent.com/37617145/47660283-a9e7f900-dbd1-11e8-87d9-38c47110ef8f.png)

**Comment by bille18** [comment]
未确认，后台已经修补,debug版是不能分享。release 才能分享.Fixed #636
