### ISSUE TITLE
所有的教程需要更新

### ISSUE THREAD

**Issue by caiyuanzi2018** [eostoken/wallet#655]
![image](https://user-images.githubusercontent.com/37617145/48324104-662dce80-e66a-11e8-9e3e-8daa93878aa0.png)

**Comment by marcoLuo** [comment]
1、如何导入私钥
2、创建钱包教程
3、激活钱包教程

**Comment by marcoLuo** [comment]
1、如何导入私钥: https://w.url.cn/s/ADZhNPk
2、创建钱包教程:https://w.url.cn/s/Ajzb1mm
3、激活钱包教程:https://w.url.cn/s/Ajzb1mm
