### ISSUE TITLE
【ios】联系人界面功能逻辑不通！    联系人名字 需求图上是可以输入中文的

### ISSUE THREAD

**Issue by caiyuanzi2018** [eostoken/wallet#665]
![image](https://user-images.githubusercontent.com/37617145/48330693-794f9700-e688-11e8-8747-789582b751e8.png)
![image](https://user-images.githubusercontent.com/37617145/48330720-8ec4c100-e688-11e8-99ef-4a269ad96390.png)

**Comment by bille18** [comment]
issue #665 , 可以选择
