### ISSUE TITLE
Quagaggah....是未激活的账号！这里逻辑错误！

### ISSUE THREAD

**Issue by caiyuanzi2018** [eostoken/wallet#670]
![image](https://user-images.githubusercontent.com/37617145/48335002-67292500-e697-11e8-8ae0-133bfada4a8c.png)

**Comment by Ben002** [comment]
已解决，详见：
commit a6f34aea29de3c89690a5dd419f87ba514e2a8e2

**Comment by caiyuanzi2018** [comment]
还未修复
![image](https://user-images.githubusercontent.com/37617145/48398747-96559a00-e75c-11e8-9090-18df56928d92.png)
