### ISSUE TITLE
忘记密码、注册界面获取不了验证码！

### ISSUE THREAD

**Issue by caiyuanzi2018** [eostoken/wallet#736]
![image](https://user-images.githubusercontent.com/37617145/48527721-0da73d00-e8c7-11e8-86da-6464fc4ad798.png)
![image](https://user-images.githubusercontent.com/37617145/48527743-1ef04980-e8c7-11e8-8681-5fc5ac119357.png)

**Comment by bille18** [comment]
Fixed #736,已解决
