### ISSUE TITLE
Daap从搜索栏访问的游戏，连接不一样 logo全部一样

### ISSUE THREAD

**Issue by caiyuanzi2018** [eostoken/wallet#738]
![image](https://user-images.githubusercontent.com/37617145/48528397-c2daf480-e8c9-11e8-87ef-0e986c5238b1.png)

**Comment by bille18** [comment]
Fixed #738 ,通过搜索栏，输入url 访问，app 只能获取到url ，没有获取到 logo地址和name 给app. 保存历史记录时，默认一个logo地址保存到历史记录。以保证打开历史记录时logo 有图片，否则logo就会白屏很难看。　搜索栏输入的游戏，在后台没有登记，没有录入logo.  　该问题，只能如此处理. 不解决.
